---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: const universidad = edificios[edificios.length]
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: const universidad = edificios[edificios.length-1]
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: const universidad = edificios[3]
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: const universidad = edificios["universidad"]
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: const universidad = edificios[last]
  checked: false
name: Último elemento
